server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
<<<<<<< HEAD
        server-addr: localhost:8848 #配置Nacos地址
        # 换成nginx的1111端口，做集群
        #server-addr: 127.0.0.1:1111
=======
        #server-addr: localhost:8848 #配置Nacos地址
        # 换成nginx的1111端口，做集群
        server-addr: 127.0.0.1:1111
>>>>>>> 136072e8de660f078c0b426f93922e8fa4fa1edd
