server:
  port: 3344

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sugoile/SpringCloud-Config-Test.git   #GitHub上面的git仓库名字
          search-paths: SpringCloud-Config-Test   #搜索目录
          default-label: main                     #默认读取分支
          username: github账号
          password: github密码

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    register-with-eureka: true
    fetch-registry: true
