server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_get         #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001     #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**         # 断言，路径相匹配的进行路由

        - id: payment_serverport  #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/serverport         # 断言，路径相匹配的进行路由
            #- Query=smile
            #- Header=X-Request-Id, \d+  #通过 Header 属性匹配,一个 header 中属性名称和一个正则表达式，这个属性值和正则表达式匹配则执行
            #- Cookie=sessionId, test		#通过 Cookie 匹配，一个是 Cookie name ,一个是正则表达式
            #- Host=**.baidu.com				#通过 Host 匹配
            #- Method=GET						#通过请求方式匹配
            #- RemoteAddr=192.168.1.1/24		#通过请求 ip 地址进行匹配
eureka:
  instance:
    hostname: cloud-gateway-service
  #服务提供者provider注册进eureka服务列表内
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka
