server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_order
    username: root
    password: root

feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml


# 1.0新添加的enabled激活自动配置，使得我们可以在yaml/properties文件中配置，
# 避免了以前需要客户端引入2个文件：
# file.conf 和 registry.conf
seata:
  enabled: true # 1.0新特性，需要依赖seata-spring-boot-starter,默认为true
  tx-service-group: seata_tx_group
  #  transport:
  #    type: TCP #default value is TCP
  #    server: NIO #default value is NIO
  #    heartbeat: true #enable heartbeat
  #    enable-client-batch-send-request: true
  #    serialization: seata
  #    compressor: none
  #    shutdown:
  #      wait: 3 #when destroy server, wait seconds
  registry:
    type: nacos
  #      application: default
  #      weight: 1
    service:
  #    vgroup-mapping: geekplus_tx_group
      disable-global-transaction: false
      disableGlobalTransaction: false
  client:
    support:
      spring:
        datasource-autoproxy: false

#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000
#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000